version: '3.7'

services:
  bt-mqtt-gateway:
    image: zewelor/bt-mqtt-gateway
    container_name: bt-mqtt-gateway
    restart: always
    # Uncomment to enable debug
    #environment:
    #  - DEBUG=true
    volumes:
      - ./config.yaml:/application/config.yaml
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
